#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli') {
	echo "You must use the command line to run this script.\n";
	exit(1);
}

$dir = getcwd();
$files = [
	$dir . '/../../autoload.php',
	$dir . '/../vendor/autoload.php',
	$dir . '/vendor/autoload.php'
];
foreach ($files as $file) {
	if (file_exists($file)) {
		require $file;
		break;
	}
	fwrite("Composer dependencies are not installed.\n");
	die(2);
}

$json = file_get_contents(__DIR__ . "/package.json");
$app = json_decode($json);

if (!$app) {
	fwrite("Can not read package.json.\n");
	die(3);
}

$cli = new \Symfony\Component\Console\Application($app->name, $app->version);
(new \Elgg\CLI($cli))->run();
